---
application:
  root: '/projects/infinibox/cluster-app'
  env: 'development'

web:
  context: /cluster-app
  static: public
  # host:

pooling:
  messaging:
      min: 1
      max: 5

#services:
#  CreateCache:
#    config: 
#      cache_name: '//localhost/cluster-app'

tasks:
  Backgroundable:
    concurrency: 0

queues:
  /queues/cluster-app/local:
    durable: true

messaging:
  /queues/cluster-app/local:
    JmsConsumerProc:
       concurrency: 1

jobs:
  publish_notification:
    job:         JmsProducerJob
    cron:        '10 * * * * ?'
    description: Invoke the jms_producer_job.rb every 10 seconds
